#!/usr/bin/env python3

"""Project Euler Problem 12
The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

from utils import numDivisors
# print(numDivisors(68719476735), primeFactors(68719476735))
def main():
    n = 1 
    numdivs = numDivisors(n)
    most = numdivs
    tri = sum(range(n+1))
    tris = [n]
    try:
        while numdivs < 501:
            if numdivs > most:
                most = numdivs
                # print(n,tri, numdivs)
            n += 1
            tri = sum(range(n+1))
            tris.append(tri)
            numdivs = numDivisors(tri)
    except KeyboardInterrupt:
        print("Stopped at:", n, numdivs)
    # print(n,tri, numDivisors(tri),len(nd))
    # print(tri)
    print(sum(range(500)))
    # print(n)
    # pprint([(i,numDivisors(i)) for i in tris[-10:]])
if __name__ == '__main__':
    main()